
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PengBo.Framwork.Domain
{

    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]

    public partial class Category
    {

        public Category()
        {

            this.Product = new HashSet<Product>();

        }

        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Name { get; set; }


        [DataMember]
        public virtual ICollection<Product> Product { get; set; }

    }

}
